### ISSUE TITLE
Add instructions on the app on how to use Assist app

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/assist-capsule#22]
This issue is for both design and the actual implementation.

We need to include a "How to" guide somewhere on the app that includes the following:
1) Go to Identity app
2) Publish your DID
3) Select Assist
4) Write any custom note regarding the publish(this note won't be saved on the blockchain, is private and can only be viewable by you)
5) Publish

**Comment by mfaizanatiq** [comment]
### Instructions
[Instructions.pdf](https://github.com/tuum-tech/assist-capsule/files/4930817/Instructions.pdf

**Comment by kpachhai** [comment]
Can we also show these instructions as part of onboarding screen? And the first screen user sees Everytime the app is opened.
