### ISSUE TITLE
[Design]: Add a new service to retrieve current DID document from the blockchain

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/assist-capsule#23]
For a single DID, there may be one or multiple DID documents that are published on the blockchain. So, needs to be formatted accordingly. 
The following fields will be shown on the page for each DID document that are associated with the particular DID:

- DID: did:elastos:iouMSXKHNcwdbPzb58pXpmGBDBxrMzfq2c
- Transaction Hash: 896fde395ee59f2ebc054d315d94878f1ecd94ac35ff1e74ce68e834d9542e61
- Published Time: 2020-06-08T14:49:20Z
- Verifiable Credentials(there may be one ore multiple credentials) to the same DID document:
```
    name:
    - Type: BasicProfileCredential, SelfProclaimedCredential
    - Issued on: 2020-04-27T19:21:35Z
    - Expires on: 2025-04-26T19:21:34Z
    - Details about the credential
        - name: KP Woods
```
```    
    tech.tuum.academy:
    - Type: ApplicationProfileCredential, GameApplicationProfileCredential, SelfProclaimedCredential
    - Issued on: 2020-04-27T19:21:35Z
    - Expires on: 2025-04-26T19:21:34Z
    - Details about the credential
        - Application ID: tech.tuum.academy
        - Application Type: elastosbrowser
        - Description: Learn Elastos by playing games against friends
```
Note that the details about the credential varies according to what kind of credential it is and there are many types of credentials. Instead of designing for each of those credentials, let's create a basic template that we can use and the content can be filled dynamically from the application side.

**Comment by mfaizanatiq** [comment]
[Assist dApp.pdf](https://github.com/tuum-tech/assist-capsule/files/4896262/Assist.dApp.pdf)

**Comment by mfaizanatiq** [comment]
![image](https://user-images.githubusercontent.com/7628901/88311151-996e9f00-cd21-11ea-9bd4-f526fb7c252f.png)
