### ISSUE TITLE
Design popup

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/assist-capsule#25]
We need to create a template design for popups that we can use throughout the app.
Take a look at the following current popups below and let's come up with a nice looking popup design that we will then implement in the app.

**Comment by mfaizanatiq** [comment]
### 1. Simple
![image](https://user-images.githubusercontent.com/7628901/87030407-9b4d4400-c1f2-11ea-8c48-16698943df6e.png)

### 2. Success
![image](https://user-images.githubusercontent.com/7628901/87030520-ca63b580-c1f2-11ea-89f4-9b8be8bf7ff4.png)

### 3. Error
![image](https://user-images.githubusercontent.com/7628901/87030549-d485b400-c1f2-11ea-865a-8912c55ba904.png)

### 4. Information
![image](https://user-images.githubusercontent.com/7628901/87030580-dcddef00-c1f2-11ea-93a7-c33d47e726b0.png)
