### ISSUE TITLE
Update the screen to show # of times DID publish service has been used by the user

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/assist-capsule#36]
This issue contains both design and implementation.

Need to update the first page to show the following as part of the same row that has "ID Publish"

5/10 used

The API can be accessed now. Look at
https://github.com/tuum-tech/assist-restapi-backend/issues/18

**Comment by mfaizanatiq** [comment]
### Design 01
[Publish_Design_01.pdf](https://github.com/tuum-tech/assist-capsule/files/4930803/Publish_Design_01.pdf)

### Design 02
[Publish_Design_02.pdf](https://github.com/tuum-tech/assist-capsule/files/4930807/Publish_Design_02.pdf)
