### ISSUE TITLE
Add a new section to display total # of times DID publish service has been used

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/assist-capsule#37]
This includes both design and implementation.

This is not to be confused with the individual # of times a particular user has used DID publish. 
This number should show the TOTAL number of times DID publish service has been used. 

Maybe a new section to show Assist statistics? We can also include the following(These stats are to be applied to each type of service - did publish service, media upload service, etc):
- Total number of times DID publish service has been used
- Total number of times DID publish service has been used just today
- Total number of DID users who have used DID publish service

**Comment by mfaizanatiq** [comment]
### Statistics
[Stats.pdf](https://github.com/tuum-tech/assist-capsule/files/4930819/Stats.pdf)

**Comment by kpachhai** [comment]
For total number of daily did publishes, we shouldn't show "5 of 10 requests" because this is the total number of requests . This is not a stat for the user but rather it's a summation of all the requests for today.
