### ISSUE TITLE
Chinese information in  Assist is not displayed correctly

### ISSUE THREAD

**Issue by xuliting** [tuum-tech/assist-capsule#38]

**Comment by kpachhai** [comment]
Could you explain more about this? Which Chinese information are you referring to? Do you have a screenshot?

**Comment by xuliting** [comment]
![15661594621809_ pic_hd](https://user-images.githubusercontent.com/18321471/87620163-6d1ab780-c750-11ea-975b-9caa3eaa63aa.jpg)

**Comment by kpachhai** [comment]
Ah I see what you mean. Thanks for reporting.
